### ISSUE TITLE
Change icon picker in meta-boxes

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/cpo-content-types#1]
Vreau icon picker-ul pe care-l folosim in Alpha. In rahatul asta de icon picker, nici macar nu poti acum sa faci un search.

**Comment by giucu91** [comment]
@cristianraiber nu prea merge ca asta in tema a folosit pentru font awesome coduri de genul : `&#xf000` si iconpickerul ala foloseste clase si ca sa stau sa iau pentru fiecare clasa codul ala nu stiu daca e ceea ce vrem noi sa facem. Pe langa asta vad ca in cod exista si linearicons si typeicons.
